-- MySQL Script generated by MySQL Workbench
-- 09/10/16 14:30:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema clothing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clothing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clothing` DEFAULT CHARACTER SET utf8 ;
USE `clothing` ;

-- -----------------------------------------------------
-- Table `clothing`.`jackets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothing`.`jackets` (
  `JACKETS_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `SHOP` VARCHAR(45) NOT NULL,
  `PRICE` DOUBLE NOT NULL,
  `SIZE` INT(11) NOT NULL,
  PRIMARY KEY (`JACKETS_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clothing`.`shirts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothing`.`shirts` (
  `SHIRTS_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `SIZE` INT(11) NOT NULL,
  `PRICE` DOUBLE NOT NULL,
  `SHOP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SHIRTS_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clothing`.`shoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clothing`.`shoes` (
  `SHOES_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `SIZE` INT(11) NOT NULL,
  `SHOP` VARCHAR(45) NOT NULL,
  `PRICE` DOUBLE NOT NULL,
  PRIMARY KEY (`SHOES_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
